[tool.poetry]
name = "wattson"
version = "0.1.0"
description = "An application for visualizing the health of system batteries."
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "wattson", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.10"
numpy = "^2.2.6"
pydantic = "^2.11.4"
mysql-connector-python = "^9.3.0"
python-dotenv = "^1.1.0"
pandas = "^2.2.3"
ipykernel = "^6.29.5"
matplotlib = "^3.10.3"
pytest = "^8.3.5"
dask = "^2025.5.1"
sqlalchemy = "^2.0.41"
scipy = "^1.15.3"
ipympl = "^0.9.7"
pyarrow = "^21.0.0"
pymysql = "^1.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
